### ISSUE TITLE
docker环境运行，无法下载模型

### ISSUE THREAD

**Issue by jiangjingping** [sugarforever/chat-ollama#148]
用docker拉取最新镜像后，输入模型名称,点击download，无反应，后台报错：
![image](https://github.com/sugarforever/chat-ollama/assets/14227549/d8b5ba6a-6b8e-49dd-a9c1-a4bda989e76b)

**Comment by kamly** [comment]
me too

**Comment by XePope** [comment]
通过docker文件分析，我看是是使用宿主机ollma环境，所以你需要再宿主机上安装ollama，通过宿主机的ollama 拉取模型。
另外需要注意：
1.宿主机启动ollama run serve
2.保证容器内能访问宿主机上的ollama服务，在容器内通过curl测试访问宿主机的ollama服务。

**Comment by jiangjingping** [comment]
> me too, but i try host:
> 
> `ollama:11434`
> 
> it work~
> 
> <img alt="image" width="694" src="https://private-user-images.githubusercontent.com/15706085/316321844-abbbb2cb-3722-4ffc-a100-0200fec9de1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzQ0MjYsIm5iZiI6MTcxMTM3NDEyNiwicGF0aCI6Ii8xNTcwNjA4NS8zMTYzMjE4NDQtYWJiYmIyY2ItMzcyMi00ZmZjLWExMDAtMDIwMGZlYzlkZTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEzNDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NTJkZjhiMTJlYjdhZGVlYjQ2OWZlMGViNjBkMTAzNjAzMWZmNTliYTUzZGRhNzhhZDU4MzA1MDk1YjY4NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2S2P8CaNGGVEPq_zac0IX7sUL44d3aigU41ZGflWeU">

it didn't work for me T_T, are you running docker ?

**Comment by jiangjingping** [comment]
@kamly it didn't work for me ...

**Comment by jiangjingping** [comment]
@XePope 我这里按照文档配置的，宿主机也运行者ollama服务，但还是不行，通过容器内的curl访问宿主机不通。

**Comment by kamly** [comment]
> me too, but i try host:
> 
> `ollama:11434`
> 
> it work~
> 
> <img alt="image" width="694" src="https://private-user-images.githubusercontent.com/15706085/316321844-abbbb2cb-3722-4ffc-a100-0200fec9de1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDkxODMsIm5iZiI6MTcxMTQwODg4MywicGF0aCI6Ii8xNTcwNjA4NS8zMTYzMjE4NDQtYWJiYmIyY2ItMzcyMi00ZmZjLWExMDAtMDIwMGZlYzlkZTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIzMjEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjOGZkN2JkZWY1NmE5N2ZiZjYwMjM5OWM5OGNkZjI4M2E0N2ZmMDcyMjRiZmMwOTU2MTZiMmMyZTUwYjhkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CNnKpfBgPG6rRxJcN2PvDEW5JSUno46IQm6xZlaGh8">

docker-composer.yaml

```yaml
version: '3.1'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./chromadb_data:/chroma/.chroma/index

  chatollama:
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
    image: 0001coder/chatollama:latest
    ports:
      - "8899:3000"
    pull_policy: always
    restart: always
    volumes:
      - ./chatollama:/app/sqlite

volumes:
  chromadb_data:
```
