### ISSUE TITLE
关于容器启动后需要pnpm run prisma-migrate 的问题

### ISSUE THREAD

**Issue by hootinwang** [sugarforever/chat-ollama#256]
```
version: '3.1'
services:
  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - ollama
  chromadb:
    image: chromadb/chroma
    restart: always
    volumes:
      - ./chromadb_data:/chroma/.chroma/index
    networks:
      - ollama

  chatollama:
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
      - REDIS_HOST=redis
    image: 0001coder/chatollama:latest
    ports:
      - "3000:3000"
    pull_policy: always
    restart: always
    volumes:
      - ./chatollama:/app/sqlite
    networks:
      - ollama

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - ollama

networks:
  ollama:
   driver: bridge
```
按照以上docker-compose.yaml 启动容器后, 还需要进入到容器手动执行 `pnpm run prisma-migrate` , 可以在dockerfile内去 `pnpm run prisma-migrate` 吗
