### ISSUE TITLE
在做rag查询到的时候一直出错

### ISSUE THREAD

**Issue by dafei1288** [sugarforever/chat-ollama#3]
在做rag查询到的时候一直出错

【nuxt】 【request error】 【unhandled】 【500】 Chroma getOrCreateCollection error: Error: TypeError: fetch failed
  at Chroma.ensureCollection (/D:/working/opensource/chat-ollama/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Chroma.similaritySearchVectorWithScore (/D:/working/opensource/chat-ollama/node_modules/@langchain/community/dist/vectorstores/chroma.js:187:28)    
  at async Chroma.similaritySearch (/D:/working/opensource/chat-ollama/node_modules/@langchain/core/dist/vectorstores.js:104:25)
  at async VectorStoreRetriever.getRelevantDocuments (/D:/working/opensource/chat-ollama/node_modules/@langchain/core/dist/retrievers.js:67:29)
  at Object.handler (D:\working\opensource\chat-ollama\server\api\models\chat\index.post.ts:67:1)

使用的 chroma 配置如下

```
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      - ./chroma-data:/chroma/chroma/
    ports:
      - 8011:8000
```
