### ISSUE TITLE
如何进行配置调整，比如增加COHERE_API_KEY

### ISSUE THREAD

**Issue by zmm1996** [sugarforever/chat-ollama#386]
想要更改.env配置中的COHERE_API_KEY需要怎么做

**Comment by satrong** [comment]
在 .env 文件中配置中（参考下面代码），然后重启一下 chat-ollama（docker 容器）
```
COHERE_API_KEY=<your key>
```

**Comment by sugarforever** [comment]
> COHERE_API_KEY

如果你使用的docker版本，请在docker-compose.yaml中作如下修改，添加COHERE_API_KEY环境变量

```
  chatollama:
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
      - REDIS_HOST=redis
      - COHERE_API_KEY=${COHERE_API_KEY}
    image: 0001coder/chatollama:latest
    ports:
      - "3000:3000"
    pull_policy: always
    restart: always
    volumes:
      - ~/.chatollama:/app/sqlite
````

然后在.env中添加对应的环境变量与值
```
COHERE_API_KEY=xxx
```
