### ISSUE TITLE
rerank 模型无法下载，如何配置

### ISSUE THREAD

**Issue by magicye** [sugarforever/chat-ollama#480]
![image](https://github.com/sugarforever/chat-ollama/assets/45220886/3a62a2c9-1e62-47dc-a193-9b25d41d0045)

**Comment by sugarforever** [comment]
你能访问 HF 国内镜像吗？https://hf-mirror.com/

可以的话，在 docker-compose.yaml 里添加HF_ENDPOINT环境变量

```
  peanutshell:
    image: ghcr.io/sugarforever/peanut-shell:latest
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
    volumes:
      - hf_data:/root/.cache
```

你试试这样是否可行
